monolog:
  handlers:
    file_log:
      type: stream
      level: debug
      path: '/var/log/dev.log'
      buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      tag: 'Skeleton Service'
    syslog_handler:
      type: syslog
      level: debug

