variables:
  DOCKER_DRIVER: overlay2
  PHP_TEST_IMAGE_VERSION: 13690


stages:
  - codestyle
  - tests
  - package
  - release-to-production

codestyle:
  stage: codestyle
  image: hub.iristrace.com/iristrace/php-test:$PHP_TEST_IMAGE_VERSION
  before_script:
    - cd service && composer install --dev
  script:
    - ./vendor/bin/phpstan analyse src
    - ./vendor/bin/phpcs src

tests:
  stage: tests
  image: hub.iristrace.com/iristrace/php-test:$PHP_TEST_IMAGE_VERSION
  before_script:
      - cd service && composer install --dev
      - cd .. && sh update-files.sh
  script:
    - pwd
    - cd service && php ./vendor/bin/phpunit tests


create-docker-image:
  stage: package
  except:
    - tags
  services:
    - docker:dind
  script:
    - docker login -u $HUB_USER -p $HUB_PASSWORD hub.iristrace.com
    - docker build --build-arg php_version=8.0-apache -t hub.iristrace.com/iristrace/skeleton-service:$CI_PIPELINE_ID  -t hub.iristrace.com/iristrace/skeleton-service:latest .
    - docker push hub.iristrace.com/iristrace/skeleton-service:$CI_PIPELINE_ID
    - docker push hub.iristrace.com/iristrace/skeleton-service:latest



release-to-production-stage:
  stage: release-to-production
  script:
    - echo "Properly done. This pipeline won't be automatically released to production on K8S next api upgrade"
  allow_failure: false
  when: manual
